# 把kuard部署到k8s上
# 作用相当于该命令docker run -d --name kuard --publish 8080:8080 gcr.io/kuar-demo/kuard-amd64:blue
apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
